name: Trigger auto deployment for file-transfer

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/file-transfer-AutoDeployTrigger-1b2fe3df-8684-4669-a978-dec68fdcaa18.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml
        env:
          SPRING_DATASOURCE_URL: ${{secrets.MYSQL_URL}}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          SPRING_MAIL_HOST: ${{ secrets.MAIL_HOST}}
          SPRING_MAIL_PORT: ${{secrets.MAIL_PORT}}
          SPRING_MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
          SPRING_MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}

      #- name: Build and Push Docker image
        #uses: mr-smithers-excellent/docker-build-push@v6
#        with:
#          image: ${{secrets.DOCKERHUB_IMAGE_NAME}}
#          tags: ${{ github.sha }}
#          dockerfile: 'backend/Dockerfile'
#          context: backend
#          registry: docker.io
#          username: ${{ secrets.FILETRANSFER_REGISTRY_USERNAME }}
#          password: ${{ secrets.FILETRANSFER_REGISTRY_PASSWORD }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FILETRANSFER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FILETRANSFER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FILETRANSFER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: backend/Dockerfile
          registryUrl: registry.hub.docker.com
          registryUsername: ${{ secrets.FILETRANSFER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FILETRANSFER_REGISTRY_PASSWORD }}
          imageToBuild: registry.hub.docker.com/${{secrets.DOCKERHUB_IMAGE_NAME}}:${{ github.sha }}
          containerAppName: file-transfer
          resourceGroup: ${{secrets.AZURE_RESOURCE_GROUP}}
          buildArguments: |
            MYSQL_URL=${{secrets.MONGODB_URL}}
            MYSQL_USERNAME=${{secrets.MYSQL_USERNAME}}
            MYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD}}
            MAIL_HOST=${{secrets.MAIL_HOST}}
            MAIL_PORT=${{secrets.MAIL_PORT}}
            MAIL_USERNAME=${{secrets.MAIL_USERNAME}}
            MAIL_PASSWORD=${{secrets.MAIL_PASSWORD}}

          #containerAppEnvironment: ${{secrets.AZURE_CONTAINER_APP_ENVIRONMENT}}
          #targetPort: 8080

