
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file backend/pom.xml

      env:
        MYSQL_URL: ${{secrets.MYSQL_URL}}
        MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MAIL_HOST: ${{ secrets.MAIL_HOST}}
        MAIL_PORT: ${{secrets.MAIL_PORT}}
        MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
        MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with: 
        push: true
        tags: ${{ secrets.DOCKERHUB_IMAGE_NAME }}:latest
        context: backend
        file: backend/Dockerfile


